### ISSUE TITLE
dashboard startup error kind-icon/:config: Symbol’s value as variable is void: corfu-margin-formatters

### ISSUE THREAD

**Issue by wereket** [Lambda-Emacs/lambda-emacs#17]
Error (use-package): kind-icon/:config: Symbol’s value as variable is void: corfu-margin-formatters Disable showing Disable logging

https://vimeo.com/manage/videos/735736151

**Comment by mclearc** [comment]
Closed by https://github.com/Lambda-Emacs/lambda-emacs/commit/4d907ec72fc21859f9321b2e81476e9a7a3f56b0
