### ISSUE TITLE
Where to change the default notes location?

### ISSUE THREAD

**Issue by anthrolisp** [Lambda-Emacs/lambda-emacs#26]
I am unable to find where to change the default notes location. At the moment denote create notes in ~/Documents/notes . Thank you in advance!

**Comment by mclearc** [comment]
In the lem-setup-notes.el file (or via `M-x customize-variable`) you should see the option 

```emacs-lisp
(defcustom lem-notes-dir nil
  "Set a directory path for notes."
  :group 'lambda-emacs
  :type 'string)
```

So just do something like, e.g., `(setq lem-notes-dir "dir/path/to/notes") and you should get the behavior you want.

**Comment by anthrolisp** [comment]
I tried adding this -- (setq lem-notes-dir "dir/path/to/notes") -- to the config.el file (changing the location to "~/Dropbox/org/") but to no avail. Denote still save to "~/Documents/notes".

**Comment by mclearc** [comment]
if you're using denote you need to set the denote notes folder as well. So here's how I have things for an example:

```emacs-lisp
(setopt lem-notes-dir (concat (getenv "HOME") "/Documents/notes/")
        denote-directory (concat lem-notes-dir "denotes/")
        denote-known-keywords '("emacs" "teaching" "unl" "workbook")
        denote-prompts '(title keywords subdirectory)
        consult-notes-denote-display-id t
        citar-denote-subdir t)
```
Use `setq` instead of `setopt` if you're on emacs 28.x or earlier.

**Comment by mclearc** [comment]
Has your issue been resolved?
