### ISSUE TITLE
How can we use the build-in version org

### ISSUE THREAD

**Issue by ifinkelstein** [Lambda-Emacs/lambda-emacs#28]
Hello and thanks for a phenomenal emacs distro!

How can we prevent `straight` from cloning and building `org`? I am trying to use the built-in org (9.5.5) because the latest `org` breaks `org-roam` (see https://github.com/org-roam/org-roam/issues/2361#issue-1793138787)

I've attempted to follow the [straight README](https://github.com/radian-software/straight.el) by including this right below the `straight` bootstrap code:
```(straight-use-package '(org :type built-in))```

I also have the following in `lem-setup-org-base.el`:
```
(use-package org
  :straight (:type built-in) ;; let straight handle this, but use built-in
...
```
Launching lambda emacs with the `-minimal` switch doesn't attempt to clone and build `org`.

However, allowing all lem and user packages results in straight cloning/building `org`, possibly as a dependency of another package. In those cases, `M-x org-version` returns `Org mode version 9.7-pre (release_9.6.7-570-gd6f3ae @ /Users/ilya/.config/emacs-lambda/var/straight/build/org/)`

`M-x lem-emacs-version` returns

`GNU Emacs 29.0.90 (build 2, aarch64-apple-darwin22.4.0, NS appkit-2299.50 Version 13.3 (Build 22E252))
 of 2023-05-12`

**Comment by ifinkelstein** [comment]
As a follow-up, perhaps you may want to default to built-in org and allow a switch for letting `straight` handle it.

**Comment by mclearc** [comment]
There isn't anything special about how I pull in org via straight, so if you want to use the built-in org, then just follow the straight directions by, for example, [pinning packages](https://github.com/radian-software/straight.el#how-do-i-pin-package-versions-or-use-only-tagged-releases).

I am going to just switch over to using the built-in package manager when Emacs 29 is officially released, as that will include the ability to pull from vc repositories and hosting like github. You can also just use that branch (package.el branch) now if you prefer.

**Comment by ifinkelstein** [comment]
Ah, ok. That's what I've been doing. Dropping `straight` as a requirement will make a lot of sense once Emacs 29 is out. 

Should be soon: https://lists.gnu.org/archive/html/emacs-devel/2023-07/msg00704.html
