### ISSUE TITLE
Just tried to use evil on lambda but got many keybind or shortcut not working

### ISSUE THREAD

**Issue by Moanrisy** [Lambda-Emacs/lambda-emacs#29]
Should I just use emacs normal keybind? instead of using evil?

Do you think it's worth it to customize it to suit evil or
just learn the way emacs move and just use pure emacs?

**Comment by mclearc** [comment]
> Should I just use emacs normal keybind? instead of using evil?

I used to use evil but it really can get in the way of some emacs functionality unless you spend a lot of time setting it up. This is partly why I like meow so much since you get the advantages of modal editing but you're still basically just using emacs keybindings for most things.

**Comment by mclearc** [comment]
I should probably also say that I don't really test the evil stuff any more so the config is really oriented towards vanilla emacs bindings or something like meow.

**Comment by Moanrisy** [comment]
Does this already included meow? First time heard of it but look interesting. 


I'm not sure if I find meow in here. 
;; *Loading default setup of 𝛌-Emacs Modules*


Try to search meow, the word only found in lem-setup-vc. 
Vc version control right? 


So it didn't included meow by default, but I can install it manually as alternative of evil that didn't break most of the shortcuts or keybinds?

**Comment by mclearc** [comment]
yeah the only keybindings that are "officially" in lambda are in lem-setup-keybindings. But I've attached my meow setup, which you could add (and obviously change to your liking) as part of your specific config. 
[cpm-setup-meow.el.zip](https://github.com/Lambda-Emacs/lambda-emacs/files/14813773/cpm-setup-meow.el.zip)
