### ISSUE TITLE
startup error

### ISSUE THREAD

**Issue by wereket** [Lambda-Emacs/lambda-emacs#3]
https://github.com/wereket/lambda-emacs/blob/main/.local/lambda-library/lambda-user/config.el#L76

Error (use-package): org-contrib/:config: Symbol’s value as variable is void: homebrew Disable showing Disable logging
Error (use-package): ox/:catch: Symbol’s value as variable is void: homebrew Disable showing Disable logging
Error (use-package): org-contrib/:config: Symbol’s value as variable is void: homebrew Disable showing Disable logging
Error (use-package): ox/:catch: Symbol’s value as variable is void: homebrew Disable showing Disable logging

**Comment by mclearc** [comment]
Thanks -- sorry, this was my mistake. Will fix soon.
