### ISSUE TITLE
unavailable package on clean install

### ISSUE THREAD

**Issue by ddpphh33** [Lambda-Emacs/lambda-emacs#30]
I started with a clean git clone and get the following message.
Error (use-package): Failed to install pcmpl-git: Package ‘pcmpl-git’ is unavailable

**Comment by mclearc** [comment]
Thanks! Can you tell me what version of Emacs you're using?

**Comment by mclearc** [comment]
Looking more closely I think I can actually remove that package. [pcmpl-args.el](https://github.com/JonWaltman/pcmpl-args.el) seems like it provides all the necessary git support.

**Comment by ddpphh33** [comment]
Works fine now.
Now I have no excuses to start work.
