### ISSUE TITLE
symbol's value as variable is void lem-local-bin

### ISSUE THREAD

**Issue by wereket** [Lambda-Emacs/lambda-emacs#4]
fresh install 
I get on startup 
symbol's value as variable is void lem-local-bin

**Comment by mclearc** [comment]
thanks -- I see it too. I think it's a bug from some updates I've done. Gimme a minute

**Comment by mclearc** [comment]
ok - try it now.

**Comment by mclearc** [comment]
hi @wereket -- any update on whether you're still seeing problems with the latest changes?

**Comment by wereket** [comment]
issue resolved
